version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./src/:/opt/pythia/src/
      - ./local-docker/run.py:/opt/pythia/run.py
    environment:
      - FLASK_ENV=development
    command: python run.py
